apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: java-prom-29524-2 
  janus-idp.io/tekton: java-prom-29524-2
  backstage.io/kubernetes-id: java-prom-29524-2
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: java-prom-29524-2
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  